[time]
maxcfl = 0.5  # Maximum allowed CFL number

[dimensions] 
# Padded and unpadded resolutions can either be determined automatically
# or specified explicitly.

# If nx = -1 and padded_nx = something positive,
# then an optimal nx for that padded_nx will be determined.

# If padded_nx = -1 but nx is specified, then the system chooses
# the minimum padded_nx that works.

# If both are specified, then they are used as given.

# N.B. The automatic resolution search supports only quadratic nonlinearities
# via the 3/2 rule.
nx = -1
ny = -1
nz = -1

padded_nx = -1
padded_ny = -1
padded_nz = -1

# Box dimensions must be specified
Lx = -1
Ly = -1
Lz = -1


# Finding optimal padded resolutions

# Prime numbers
padded_primes = [2, 3]
# Order of the nonlinear term
nonlinear_order = 2

[setup]
# If true, solver will measure its performance for setup.timing_steps time steps, then quit
# No output files will be written.
timing = false
timing_steps = 1000  # see above

include_lin = true  # include linear terms
include_nl = true  # include nonlinear terms

# Crank-Nicolson implicitness parameter
alpha = 0.5

[init]
rand_seed = 113  # seed for random-number generation
restart = false
restart_time = -1.0
restart_file = ""
type = "white_noise"
amplitude = 1.0

[output]

[output.0d]
save_steps = -1
diags = []

[output.1d]
save_steps = -1
diags = []

[output.2d]
save_steps = -1
diags = []

[output.3d]
save_steps = -1
diags = []

[hyper]
perphypervisc = 0.0
perphypervisc_halfpower = 2
parhypervisc = 0.0
parhypervisc_halfpower = 2
