[time]
max_cfl = 0.2  # Maximum allowed CFL number
dt_mult_increase = 1.10 # Factor by which the timestep is allowed to increase
dt_mult_decrease = 0.75 # Factor by which the timestep is decreased (only used if precomputing)
dt_mult_steps = 10000  # Number of steps before the timestep can be increased
dt_method = "continuous"

[dimensions] 
# Padded and unpadded resolutions can either be determined automatically
# or specified explicitly.

# If nx = -1 and padded_nx = something positive,
# then an optimal nx for that padded_nx will be determined.

# If padded_nx = -1 but nx is specified, then the system chooses
# the minimum padded_nx that works.

# If both are specified, then they are used as given.

# N.B. The automatic resolution search supports only quadratic nonlinearities
# via the 3/2 rule.
nx = -1
ny = -1
nz = -1

padded_nx = -1
padded_ny = -1
padded_nz = -1

# Box dimensions must be specified
Lx = -1.0
Ly = -1.0
Lz = -1.0


# Finding optimal padded resolutions

# Prime numbers
padded_primes = [2, 3]
# Order of the nonlinear term
nonlinear_order = 2

[setup]
# If true, run a linear-only simulation
linear = false

# Crank-Nicolson implicitness parameter
alpha = 0.5

# Whether the linear matrix should be computed each time step or precomputed
precompute_linear_matrix = false

# Whether to perform some predefined health checks (e.g., linear spectrum against a reference)
check_linear_matrix = true

# Generic hyperdissipation that is added to the linear matrix of any system.
# The terms are of the form
# hyper = coefficient * (k        )**(2 * power),
# unless normalised, where we have 
# hyper = coefficient * (k / k_max)**(2 * power),
# where 'coefficient' is perp, kx, ky, or kz.
# Set the coefficient to a negative number to disable.
# If set to be adaptive, the coefficient is rescaled by 1/dt at each timestep, 
# such that the amplitude of a purely dissipated mode is multiplied at each step 
# by (1 - (1 - alpha) * hyper) / (1 + alpha * hyper)

[hyperdissipation]
perp = -1.0
perp_power = 2
perp_adaptive = false
perp_normalised = false

kx = -1.0
kx_power = 2
kx_adaptive = false
kx_normalised = false

ky = -1.0
ky_power = 2
ky_adaptive = false
ky_normalised = false

kz = -1.0
kz_power = 2
kz_adaptive = false
kz_normalised = false

[forcing]
method = ""

[output]

[output.0d]
save_steps = -1
diags = []
type = "netcdf4"

[output.1d]
save_steps = -1
diags = []
type = "netcdf4"

[output.2d]
save_steps = -1
diags = []
type = "netcdf4"

[output.3d]
save_steps = -1
diags = []
type = "netcdf4"

[output.realspace]
save_steps = -1
diags = []
type = "netcdf4"

[output.realspace1d]
save_steps = -1
diags = []
type = "netcdf4"

[output.realspace2d]
save_steps = -1
diags = []
type = "netcdf4"

[output.realspace3d]
save_steps = -1
diags = []
type = "netcdf4"

[output.eigensystem]
save_steps = -1
diags = []
type = "netcdf4"
