[time]
max_cfl = 0.5  # Maximum allowed CFL number
dt_multiplier = 1.5 # Factor by which the timestep is allowed to increase

[dimensions] 
# Padded and unpadded resolutions can either be determined automatically
# or specified explicitly.

# If nx = -1 and padded_nx = something positive,
# then an optimal nx for that padded_nx will be determined.

# If padded_nx = -1 but nx is specified, then the system chooses
# the minimum padded_nx that works.

# If both are specified, then they are used as given.

# N.B. The automatic resolution search supports only quadratic nonlinearities
# via the 3/2 rule.
nx = -1
ny = -1
nz = -1

padded_nx = -1
padded_ny = -1
padded_nz = -1

# Box dimensions must be specified
Lx = -1
Ly = -1
Lz = -1


# Finding optimal padded resolutions

# Prime numbers
padded_primes = [2, 3]
# Order of the nonlinear term
nonlinear_order = 2

[setup]
# If true, run a linear-only simulation
linear = false

# Crank-Nicolson implicitness parameter
alpha = 0.5

# Whether the linear matrix should be computed each time step or precomputed
precompute_linear_matrix = false

[output]

[output.0d]
save_steps = -1
diags = []
type = "netcdf4"

[output.1d]
save_steps = -1
diags = []
type = "netcdf4"

[output.2d]
save_steps = -1
diags = []
type = "netcdf4"

[output.3d]
save_steps = -1
diags = []
type = "netcdf4"

[hyper]
perphypervisc = 0.0
perphypervisc_halfpower = 2
parhypervisc = 0.0
parhypervisc_halfpower = 2
