[time]
max_dt = 0.01  # integration time step
min_dt = 1e-8
tfinal =  10  # final time

[setup]
solver = ""  # name of the solver
system = ""  # name of the system of equations
precision = "single"  # floating-point precision

# If true, solver will measure its performance for setup.timing_steps time steps, then quit
# No output files will be written.
timing = false
timing_steps = 1000

[init]
rand_seed = 113  # seed for random-number generation
type = "white_noise"
amplitude = 1e-4

[restart]
write_restart_file = true
restart_if_exists = false
write_steps = 10000
restart_from = ""
reset_time = false

[output]
write_steps = 50000  # number of time steps between writes to the hard drive

[output.time]  # The most basic, text-based output of space-separated columns
# Each system can define additional output groups.
# The diagnostics in this output group are run every save_steps time steps.
# -1 means that the output group is not active.
save_steps = -1 

# This is a list of strings for the names of the active diagnostics.
# Each system defines a dict called diags_dict where the names of the
# diagnostics are mapped to the diagnostic classes.
diags = []

# Currently supported types are "text" and "netcdf4", where the former is a
# text file of space-separated columns where each row corresponds to a
# different scalar quantity. The first row contains the names of the columns.
# The first three columns are always current_step, current_time, and
# current_dt.
type = "text"
